### PR TITLE
Couple of improvements

### PR DESCRIPTION
**Pull request by philwareham**

### CODE REVIEW

**Comment by MrQwest** [comment]
Hey Phil, I'm curious to know why you removed the box-sizing on everything?

**Comment by philwareham** [comment]
I can't see a reason for it to be on everything (although I'm open to suggestions of why it was, that I may have missed). From my experience, box-sizing is a last-resort type kind of rule for if you have no other option than to override the box model so that it counts padding/border or suchlike - say for if you need a form input box to be width:100% but you have padding on the input, or for a responsive container that is 100%.

In fact, I'll probably submit a patch soon to remove it from the section tags, since in this case that can be done with some clever use of percentage widths instead.

Main two reasons for removing it are:
1. If you use the Chrome dev tools web inspector, as I frequently do, then that rule keeps appearing when I inspect and element.
2. Applying rules via \* {} is non-performant - [see here for a good summary](http://net.tutsplus.com/tutorials/html-css-techniques/the-30-css-selectors-you-must-memorize/) (it's point 1)

Going back to the web inspector - I'd recommend the awesome [Normalize](http://necolas.github.com/normalize.css/) instead of the old 'reset all' type of reset CSS. Makes using the web inspector a dream (since you don't see all the annoying reset rules).

**Comment by MrQwest** [comment]
Fair comments. I added it in in the first place after reading Paul Irish's comments on it here (http://paulirish.com/2012/box-sizing-border-box-ftw/).  For me, it puts the box model on a level playing field and everything seems to work nicely when it comes to lining things up.

I'll look into Normalize, that might come in handy in the future.

**Comment by philwareham** [comment]
Just read that article by Paul Irish. The guy is a dude and web legend but I'm not too keen on that method suggested, we've had the box-model for years now without any significant problems (OK, maybe it's not that logical but whatever). If you want to put that rule back in I won't gripe though.

**Pull request merged**
